### ISSUE TITLE
Logarithm Kernel

### ISSUE THREAD

**Issue by aaron-bray** [clEsperanto/CLIc_prototype#102]
I know this is on your TODO list
I see there is a kernel for it already
I was wondering if we could work on this
Do you have any docs or examples of how to do this?

Thanks!

**Comment by haesleinhuepf** [comment]
Hi @aaron-bray ,

great to see you here! The function is available in CLIJ2 and pyclesperanto_prototype:
https://clij.github.io/clij2-docs/reference_logarithm

What would you like to work on? 🙃

Best,
Robert

**Comment by StRigaud** [comment]
Hi @aaron-bray 

You are very welcome to participate in any form you see fit, adding a new kernel function is a good starting point!

The [`logarithm.cl`](https://github.com/clEsperanto/clij-opencl-kernels/blob/clesperanto_kernels/kernels/logarithm.cl) kernel is ready to be integrated. 
I do not have a documentation ready yet to adding it to `Clic` but this is not a complicated one and this issue can be a good starting point.

As I said [here](https://github.com/InsightSoftwareConsortium/ITKCLEsperanto/issues/23#issuecomment-1232664034), I'm currently pushing a new version which change a bit some architecture and name aspect in the `development` branch. This should soon be merged to the `master` branch. So I would encourage you to work on a fork of the `development` branch and to do a PR once ready, so that your contribution is added to the next version.

**For adding a new kernel:**

Prior to anything, we need to have an OpenCL kernel code ready in the [kernel repository](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels). This is already the case here, so we can skip.

Then, we need to create a `LogarithmKernel` class (`.hpp` and `.cpp`) in the `tier1` folder. If the new kernel were to rely on an already existing kernel in the `tier1`, we would add it to the `tier2`. 
Here, you can happily copy the [`CopyKernel` class](https://github.com/clEsperanto/CLIc_prototype/blob/development/clic/include/tier1/cleCopyKernel.hpp), and replace the naming to fit the new kernel you are adding. 

__Important__, the the OpenCL parameter names must be identical to the `AddParameter()` tag argument:
```c++
// cpp side
auto
CopyKernel::SetInput(const Image & object) -> void
{
  this->AddParameter("src", object);
}

auto
CopyKernel::SetOutput(const Image & object) -> void
{
  this->AddParameter("dst", object);
}

// opencl kernel side
__kernel void copy(
    IMAGE_src_TYPE  src,  // "src" tag name
    IMAGE_dst_TYPE  dst  // "dst" tag name
) 
```

Then we would need to add the `Logarithm` method function to the [`clesperanto` class](https://github.com/clEsperanto/CLIc_prototype/blob/development/clic/include/core/clesperanto.hpp) for user to easily access it.

Finally, add a test which should run the new kernel for all accepted data type and dimensions, to make sure that the kernel is actually running correctly (both the cpp code but also the ocl code).

Do not hesitate if some things are not clear or if you have more questions.

**If I were to summarized:**

- [ ]  Create an OpenCL kernel operation
OpenCL code must be nD if possible and respect the [coding convention](https://github.com/clEsperanto/clij-opencl-kernels/blob/clesperanto_kernels/README.md)

- [ ]  Create a new class inheriting from the [Operation class](https://github.com/clEsperanto/CLIc_prototype/blob/development/clic/include/core/cleOperation.hpp)
For simple operation (tier 1), one can take example in the [`CopyKernel` class](https://github.com/clEsperanto/CLIc_prototype/blob/development/clic/include/tier1/cleCopyKernel.hpp) or the [`AddImagesWeightedKernel` class](https://github.com/clEsperanto/CLIc_prototype/blob/development/clic/include/tier1/cleAddImagesWeightedKernel.hpp).

- [ ] Add a new method to the [`clesperanto` class](https://github.com/clEsperanto/CLIc_prototype/blob/development/clic/include/core/clesperanto.hpp) 

- [ ] Provide a test validating that the kernel is running as expected

**Comment by aaron-bray** [comment]
Thank you for the information @StRigaud 

This will be a slow burn effort for me, but I will keep you posted!

**Comment by StRigaud** [comment]
Do not hesitate to ask  me with questions if you need too!

**Comment by StRigaud** [comment]
See this issues for more information on how to create a new kernel

**Comment by StRigaud** [comment]
logarithm is now available:

- https://github.com/clEsperanto/CLIc_prototype/blob/92fb217c9e0fc5d2c279778ff8fa7e293de3cd42/clic/src/tier1.cpp#L743-L752
