### ISSUE TITLE
Auto-generate target-images with default size equal to the source

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc_prototype#91]
(no urgent request; enjoy vacation/weekend/your day)

When calling any clesperanto filter like the following with a `target = None` parameter, it would be good if the resulting image would be automatically generated. Thus, if `target` is not none, `result = target`. If `target` is none, we need to create it. 

Which size it should have depends on the kernel. I propose that the kernel class per default generates a new `target` image with the same size as `source`. This default behaviour can be overwritten, e.g. the maximum_z_project would create 2D `target` images instead of the same size as `source`.

```
result = cle.filter(source = image, target = None, sigma = 5)
```

**Comment by StRigaud** [comment]
So, this is too python, and I am not sure I can fit this in C++
```result = cle.filter(source = image, target = None, sigma = 5)```

Because `cle.filter` would have its return value both as parameter and as a return statement, which may break some C++ security standards. But mainly because default parameters must be at the end, hence this call `cle.filter(image, 5)` would fail, same as in python, due to the absence of positional parameters. An alternative could be `cle.filter(image, void, 5)`, thus not sure it works.

However, in the kernel class, we could define a behaviour if the method `SetOutput()` is not called. For example:
```
AddImageAndScalar kernel (gpu);
kernel.SetInput(image);
kernel.SetScalar(5);
kernel.Execute();
```
The output is not specified, this can be detected and a default output can be create as a copy of the input. A `GetOutput()` method should be needed then to retrieve the output. 
```
auto output = kernel.GetOutput();
```
And a specific behaviour will be needed for some more complex operation kernel.


How does this translate at the user gateway interface, idk yet. So not entirely impossible but not an easy step I would say.

**Comment by StRigaud** [comment]
Done with the v0.7.0
